/**
* This file was generated by RMCFramework.
* Written by Alex Klimenko
*/


var RMCModel = function() {}

RMCModel.prototype.doRequest = function(methodName, methodParams, callback){
    var data = {
        modelName : this.modelName,
        calledMethod : methodName,
        methodProperties: methodParams
    }
    if(callback === undefined){
        return $.ajax({
            url: '{REMOTE_CALL_CONTROLLER_PASS}',
            type: 'POST',
            data: JSON.stringify(data),
            async: false,
            contentType: 'application/json; charset=utf-8'
        }).responseText;
    } else {
        $.ajax({
            url: '{REMOTE_CALL_CONTROLLER_PASS}',
            type: 'POST',
            data: JSON.stringify(data),
            contentType: 'application/json; charset=utf-8',
            success: callback
        })
    }

}

RMC =
{
{MODEL_PROTOTYPES}
    extend: function (Child, Parent) {
        var F = function() {}
        F.prototype = Parent.prototype;
        Child.prototype = new F();
        Child.prototype.constructor = Child;
        Child.superclass = Parent.prototype;
    }
}

{EXTENDS_SECTION}

{MODELS_DATA}